// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

namespace NUnitArchitecture {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using ProjectArchitecture.Model;

    public class NUnitModule_Runner_Execution : Module {

        public override string Name => "NUnit.Runner.Execution";
        public override Namespace[] Namespaces => new INode[] {
            "NUnit.Runner.Execution".AsNamespace(),
            "TestExecutionContext".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal          .TestExecutionContext                          ),
            (TypeItem) typeof( NUnit.Framework.Internal          .TestExecutionContext.IsolatedContext          ),
            (TypeItem) typeof( NUnit.Framework.Internal          .TestExecutionContext.AdhocContext             ),
            (TypeItem) typeof( NUnit.Framework.Internal          .TestExecutionStatus                           ),
            "TestExecutionContext/Facade".AsGroup(),
            (TypeItem) typeof( NUnit.Framework                   .TestContext                                   ),
            (TypeItem) typeof( NUnit.Framework                   .TestContext.TestAdapter                       ),
            (TypeItem) typeof( NUnit.Framework                   .TestContext.ResultAdapter                     ),
            (TypeItem) typeof( NUnit.Framework                   .TestContext.PropertyBagAdapter                ),
            (TypeItem) typeof( NUnit.Framework                   .TestParameters                                ),
            "WorkItemDispatcher".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.IWorkItemDispatcher                           ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.MainThreadWorkItemDispatcher                  ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher                      ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher                    ),
            "WorkItemBuilder".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkItemBuilder                               ),
            "WorkItem".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkItem                                      ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.SimpleWorkItem                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.CompositeWorkItem                             ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.CompositeWorkItem.OneTimeTearDownWorkItem     ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkItemState                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.ParallelExecutionStrategy                     ),
            (TypeItem) typeof( NUnit.Framework                   .ParallelScope                                 ),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .ITestFilter                                   ),
            (TypeItem) typeof( NUnit.Framework.Internal          .TestFilter                                    ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .ValueMatchFilter                               ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .CategoryFilter                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .IdFilter                                       ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .TestNameFilter                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .FullNameFilter                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .NamespaceFilter                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .ClassNameFilter                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .PropertyFilter                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .MethodNameFilter                               ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .CompositeFilter                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .AndFilter                                      ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .OrFilter                                       ),
            (TypeItem) typeof( NUnit.Framework.Internal.Filters .NotFilter                                      ),
            "TestCommand".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TestCommand                                   ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TestMethodCommand                             ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .EmptyTestCommand                              ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .SkipCommand                                   ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .DelegatingTestCommand                         ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands.ApplyChangesToContextCommand                   ),
            "TestCommand/Before".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .BeforeTestCommand                             ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .BeforeTestActionCommand                       ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .ConstructFixtureCommand                       ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .OneTimeSetUpCommand                           ),
            "TestCommand/After".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .AfterTestCommand                              ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .AfterTestActionCommand                        ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .DisposeFixtureCommand                         ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .OneTimeTearDownCommand                        ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .MaxTimeCommand                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TheoryResultCommand                           ),
            "TestCommand/BeforeAndAfter".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .BeforeAndAfterTestCommand                     ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TestActionCommand                             ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TestActionItem                                ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .SetUpTearDownCommand                          ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .SetUpTearDownItem                             ),
            (TypeItem) typeof( NUnit.Framework.Internal.Commands .TimeoutCommand                                ),

            "NUnit.Runner.Execution.Annotations".AsNamespace(),
            "Extensibility/CommandWrapper".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .ICommandWrapper                               ),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .IWrapSetUpTearDown                            ),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .IWrapTestMethod                               ),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .IRepeatTest                                   ),
            (TypeItem) typeof( NUnit.Framework                   .RepeatAttribute                               ),
            (TypeItem) typeof( NUnit.Framework                   .RepeatAttribute.RepeatedTestCommand           ),
            (TypeItem) typeof( NUnit.Framework                   .MaxTimeAttribute                              ),
            (TypeItem) typeof( NUnit.Framework                   .RetryAttribute                                ),
            (TypeItem) typeof( NUnit.Framework                   .RetryAttribute.RetryCommand                   ),
            "Extensibility/ContextApplier".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Interfaces        .IApplyToContext                               ),
            (TypeItem) typeof( NUnit.Framework                   .DefaultFloatingPointToleranceAttribute        ),
            (TypeItem) typeof( NUnit.Framework                   .SingleThreadedAttribute                       ),
            (TypeItem) typeof( NUnit.Framework                   .SetCultureAttribute                           ),
            (TypeItem) typeof( NUnit.Framework                   .SetUICultureAttribute                         ),
            (TypeItem) typeof( NUnit.Framework                   .ParallelizableAttribute                       ),
            (TypeItem) typeof( NUnit.Framework                   .NonParallelizableAttribute                    ),
            (TypeItem) typeof( NUnit.Framework                   .TimeoutAttribute                              ),
            "Extensibility/TestAction".AsGroup(),
            (TypeItem) typeof( NUnit.Framework                   .ITestAction                                   ),
            (TypeItem) typeof( NUnit.Framework                   .TestActionAttribute                           ),
            (TypeItem) typeof( NUnit.Framework                   .ActionTargets                                 ),

            "NUnit.Infrastructure".AsNamespace(),
            "WorkShift".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkShift                                     ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.ShiftChangeEventHandler                       ),
            "WorkShift/WorkItemQueue".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkItemQueue                                 ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.WorkItemQueueState                            ),
            "WorkShift/TestWorker".AsGroup(),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.TestWorker                                    ),
            (TypeItem) typeof( NUnit.Framework.Internal.Execution.TestWorker.TestWorkerEventHandler             ),
        }.ToHierarchy();


    }
}
